### ISSUE TITLE
How do I build this repo on my local machine?

### ISSUE THREAD

**Issue by BlackHart98** [HankBO/stata-language-server#5]
Hey, I am have issues setting up the language server on my local machine, what I mean is that when I launch the client, the language server facilities such hover, auto-completion etc. does not work. How do I get that to work? Thanks :-)

**Comment by HankBO** [comment]
> I guess there are two possible reasons. 
1.third-party python library 'pygls' was not installed sucessfully. The extension wil retry 3 times if pygls installation gets time-out error. So you may try `pip install pygls`.
2.node modules used by this extension were not installed successfully. In that case, you can open the location of the extension, then type `cd client && npm install`

Please give me response if you target and solve the problem :)

**Comment by BlackHart98** [comment]
Hey, thanks for the reply but I still could get it to build on my local machine, I already did what you recommended before I opened this issue. The is the only message in the pygls.log file "INFO:pygls.server:Starting TCP server on 127.0.0.1:2087" I don't know if you deduce anything from it.

**Comment by HankBO** [comment]
Just fix a issue #6 and update v1.1.1. You may update and have a try to see if this issue has also been solved.
