### ISSUE TITLE
Stata Language Server: Invalid python version, needs python >= 3.6

### ISSUE THREAD

**Issue by hackeye** [HankBO/stata-language-server#6]
My python is 3.9
![image](https://user-images.githubusercontent.com/25793057/150676915-6973a836-4b1e-4e35-b093-8b5165dabcfe.png)

**Comment by HankBO** [comment]
I just check the code and find the logical error about the issue. You may update v1.1.1 and try again :)

**Comment by Student144** [comment]
I have updated to v1.1.1 but still appear to be receiving this error. I have Python 3.9 installed, and have tried using the default pythonPath of "python" as well as the specific location of my installation. Is there anything else I can do to help debug?

**Comment by hackeye** [comment]
> I have updated to v1.1.1 but still appear to be receiving this error. I have Python 3.9 installed, and have tried using the default pythonPath of "python" as well as the specific location of my installation. Is there anything else I can do to help debug?

I do not know, me too

**Comment by HankBO** [comment]
I made a mistake in v1.1.1 and now v1.1.2 can check if Python's version >=3.6. The Settings of VSCode use `pythonPath`(deafult `python`). So may terminal command `python` is linked to a lower version?

**Comment by Student144** [comment]
I can confirm that I am no longer getting this error message. Thank you for such a fast fix.
